"""create subscriber foundation

Revision ID: b9e266fbce0f
Revises: 3d38b783e80f
Create Date: 2026-09-30 13:29:18.252861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e266fbce0f'
down_revision = '3d38b783e80f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name'),
    schema='public'
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'unsubscribed', 'suppressed')", name='ck_subscribers_status'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(
        'uq_subscribers_email_lower',
        'subscribers',
        [sa.text('lower(email)')],
        unique=True,
        schema='public',
    )

    op.create_table('subscriber_tag_assignments',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['public.subscribers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['public.subscriber_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscriber_id', 'tag_id'),
    schema='public'
    )
    op.create_index(
        'ix_subscriber_tag_assignments_tag_id',
        'subscriber_tag_assignments',
        ['tag_id'],
        schema='public',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_subscriber_tag_assignments_tag_id',
        table_name='subscriber_tag_assignments',
        schema='public',
    )
    op.drop_table('subscriber_tag_assignments', schema='public')
    op.drop_index(
        'uq_subscribers_email_lower',
        table_name='subscribers',
        schema='public',
    )

    op.drop_table('subscribers', schema='public')
    op.drop_table('subscriber_tags', schema='public')
    # ### end Alembic commands ###
